### ISSUE TITLE
Questions about using org-habitica first time

### ISSUE THREAD

**Issue by ymfsing** [LewWadoo/org-habitica#1]
Thanks for creating this package that meets the demand I find a long time, But when I use this package, there are some problems that bother me.

1. What is the org-habitica's task format should be?  I create a new task `** DONE test` by using org-todo, and after org-habitica-sync-task, it syncs success  with habitica and becomes `** DONE test :PROPERTIES: :HABITICA_ID: 1d971b3e-88ad-44da-b04a-f65aae7944bd :END:`. Is it a right format or process?
2. When I change the task's statu and try to org-habitica-sync-task, the message tells `org-habitica--sync-task-with-id: Symbol’s value as variable is void: update-data`. I found it in https://github.com/LewWadoo/org-habitica/blob/master/org-habitica.el#L346 , but i can't solve this problem, I guess I use the wrong format of org task.

Best wishes.

ymfsing

**Comment by LewWadoo** [comment]
> Thanks for creating this package that meets the demand I find a long time, But when I use this package, there are some problems that bother me.
> 
>     1. What is the org-habitica's task format should be?

Any correct org-heading will do.

I create a new task `** DONE test` by using org-todo, and after org-habitica-sync-task, it syncs success  with habitica and becomes `** DONE test :PROPERTIES: :HABITICA_ID: 1d971b3e-88ad-44da-b04a-f65aae7944bd :END:`. Is it a right format or process?

Absolutely correct. You should be able to find your completed task in Habitica's To Do's section, in Complete subsection.

>     2. When I change the task's statu and try to org-habitica-sync-task, the message tells `org-habitica--sync-task-with-id: Symbol’s value as variable is void: update-data`. I found it in https://github.com/LewWadoo/org-habitica/blob/master/org-habitica.el#L346 , but i can't solve this problem, I guess I use the wrong format of org task.

Your format is totally fine, but that behaviour was a bug. Please update the program to fix the issue.
